### ISSUE TITLE
Where did v9.5.4 go?

### ISSUE THREAD

**Issue by marcind** [redis/go-redis#3057]
v9.5.4 got released last Friday but today it is no longer listed under https://github.com/redis/go-redis/releases. However, I can still `go get github.com/redis/go-redis/v9@v9.5.4`. Did that release get unpublished? Is there an issue with it?

**Comment by jaredLunde** [comment]
https://pkg.go.dev/github.com/go-redis/redis/v9?tab=versions Only the prereleases are appearing under the v9 tag. Very strange.

**Comment by earl-warren** [comment]
This is an interesting test case for dependency management. The [Forgejo release pipeline](https://codeberg.org/forgejo-integration/forgejo/actions/runs/3138#jobstep-10-2354) is currently broken because of that as well as the CI.

I assume it was a mistake? Accidents happen.

**Comment by dmaier-redislabs** [comment]
Hello, 

sorry for the inconvenience. There was a sync issue in regarding releases. We are planning to release a new version soon based on the betas that were released a few weeks ago and rolled 9.5.4 back within this repo.

Regards,
David

**Comment by earl-warren** [comment]
Thanks for the update :heart: When will soon be? 

* Within 24h
* Within the next few days or weeks

Either way is fine. If it is going to happen within 24h, just waiting for it to happen is the best solution. If not reverting to a published version such as v9.5.2 is worth a little effort.

**Comment by dmaier-redislabs** [comment]
Hi,

I just wanted to update that we released v9.6 now. Again, sorry for the inconvenience that the release rollback caused.

Regards,
David

**Comment by marcind** [comment]
Thank you for the update @dmaier-redislabs .
However, I'm confused what the versioning/release strategy for this repo is. For example, the version.go file in master is still old:
https://github.com/redis/go-redis/blob/3613df6115220a276599764b54baec9dfc9d1072/version.go#L5
Looks like the v9.6 release got created from a tag/branch that has not been merged into master yet. And that version file seems to only be updated about half the time.

**Comment by MrSwed** [comment]
How to solve this problem? my project does not build with any version from 9.5 to 9.6 with this error
`github.com/redis/go-redis/extra/redisotel/v9: reading github.com/redis/go-redis/extra/redisotel/go.mod at revision extra/redisotel/v9.6.0: unknown revision extra/redisotel/ v9.6.0`.

I tried clearing caches, changing goporxy, nothing helps.

**Comment by martinsirbe** [comment]
Where did v9.5.3 go? This breaks https://github.com/TykTechnologies/tyk/issues/6424 build.

**Comment by MrSwed** [comment]
well, after many tries this works for me
```
	github.com/redis/go-redis/extra/redisotel/v9 v9.0.5
	github.com/redis/go-redis/v9 v9.5.2
```

**Comment by vladvildanov** [comment]
@MrSwed `go get github.com/redis/go-redis/v9` should update you to 9.6.0

**Comment by dmaier-redislabs** [comment]
@martinsirbe As said, there was some confusion around the next upcoming release. Because of that, we rolled the unplanned releases (9.5.3 and 9.5.4) back and replaced them by a 9.6.0 release. Sorry for the the inconvenience.

**Comment by dmaier-redislabs** [comment]
@marcind Because of the release rollback, we did speed the 9.6 release up, but we removed some of the features that are already in main (mainly search and query related stuff that we want to stabilize before releasing it to a new go-redis version). We are going to align and stabilize the main branch and will cut a new release with search and query within the next weeks.

@vladvildanov @ofekshenawa Feel free to add additional details as needed.

**Comment by mx-psi** [comment]
@dmaier-redislabs Thanks for taking a look at this issue!

Go has official guidance on what to do in these cases that I think should be followed here. Since this release was out for some time, its [code](https://proxy.golang.org/github.com/redis/go-redis/v9/@v/v9.5.4.zip) and [sumdb entry](https://sum.golang.org/lookup/github.com/redis/go-redis/v9@v9.5.4) are available in the official Go proxy, but not in this repository. This leads to two issues:
1. Users using the Go proxy will not know that this version is invalid
2. Users not using the Go proxy will have broken builds

The correct approach here is to:
1. Add a [`retract`](https://go.dev/ref/mod#go-mod-file-retract) directive for `v9.5.4` and any other failed releases
2. Add back the git tags to this repository on the original commits where they were available.

That solves both of these problems. You can see similar issues on go-chi/chi/issues/713, DataDog/agent-payload/issues/218 or openshift/api/issues/1661 where you can see how this affects your users.

**Would you consider adding the git tags back and retracting the release on the `go.mod`?**

**Comment by vladvildanov** [comment]
Thank you @mx-psi for guiding us through this process! Again we sincerely apologise for the inconvenience we caused you. We just got released a new v9.6.1 that adds a retraction for v9.5.3 and v9.5.4 to follow the best practices in go community.

**Comment by dmaier-redislabs** [comment]
Since this should be solved now, I am closing this issue. Please let us know if you should face any further issues.

**Comment by MrSwed** [comment]
Thank you!

.. extra are still old
<details><summary>Click to expand</summary>

```
>$ go get -v github.com/redis/go-redis/extra/redisotel/v9
....
go: added github.com/redis/go-redis/extra/rediscmd/v9 v9.0.5
go: added github.com/redis/go-redis/extra/redisotel/v9 v9.0.5
...
```

```
>$ go get github.com/redis/go-redis/extra/redisotel/v9@v9.6.1
go: github.com/redis/go-redis/extra/redisotel/v9@v9.6.1: invalid version: unknown revision extra/redisotel/v9.6.1
>$ go get github.com/redis/go-redis/extra/redisotel/v9@v9.6.0
go: github.com/redis/go-redis/extra/redisotel/v9@v9.6.0: invalid version: unknown revision extra/redisotel/v9.6.0
>$ go get github.com/redis/go-redis/extra/redisotel/v9@v9.5.2
go: github.com/redis/go-redis/extra/redisotel/v9@v9.5.2: invalid version: unknown revision extra/redisotel/v9.5.2

```
</details>

**Comment by dmaier-redislabs** [comment]
@MrSwed This seems to be unrelated to the accidental release of 9.5.3 and 9.5.4 because your example shows that it also happens with older versions. 

@ofekshenawa @vladvildanov Could you please open a new issue for this?
