### ISSUE TITLE
Feature Request: wrapper the  redis command as a higher interface

### ISSUE THREAD

**Issue by zj8487** [redis/go-redis#308]
Is it possible to add the interface like <a href="https://github.com/kiddouk/redisco/blob/master/redisco/containers.py">this</a>

**Comment by vmihailenco** [comment]
This deserves some thinking, but my immediate reaction is that such API is too high level for Go :)

**Comment by zj8487** [comment]
thanks for your response very much

**Comment by joonazan** [comment]
What exactly looks too high level? The major difference is that the Python code uses methods intstead of functions.

**Comment by vmihailenco** [comment]
I meant that in Python you can do something like this:

```
a = Set("set1")
b = Set("set2")
c = a - b
```

which is not possible in Go because there is no operator overloading. But otherwise this could be a good idea. Do you want to try to implement it? :)

**Comment by joonazan** [comment]
Yeah, I could do that. Another thing I've thought about is making a version
of .Result() that panics, because there is no convenient way to code one
for every type manually.

**Comment by vmihailenco** [comment]
Why Result should panic? I can imagine `Val` to panic if `err != nil`, but not `Result`...

**Comment by joonazan** [comment]
I meant that. What actually is the use-case of current Val? Ignoring errors?

**Comment by vmihailenco** [comment]
>What actually is the use-case of current Val?

Back in version 2 `Result` did not exist and there were only `Val` and `Err`. There is no good explanation why `Val` is needed, but removing it/making it panic will break too much API for a very small reason.

**Comment by joonazan** [comment]
I agree. That means it has to have another name or be in a future version /
fork.

Actually this feature request would add a completely different API and then
users would have to choose which one to use. Maybe it would make more sense
as a wrapper on top of this library.

I'll have to think about what a good API would be like. I like the
simplicity of the current API, but error handling can be painful. I am
considering panics and monads as solutions. Writing already works very
well, as you can put all the operations in a slice and loop over it.

I'll look more into it on Sunday.

**Comment by danielfbm** [comment]
+1
Actually I would even do the interfaces for the return types as well, currently they are all struct pointers that make it very hard to mock, specially because all the attributes are private

some more context:
I am trying to create a [circuit-breaker](https://gist.github.com/danielfbm/bcf036ba6a94caa160e4d749a3a9c6fe) to use in my projects, and the easiest way is to create a simple struct that can decorate the functions. Even if I use a middleware approach, I would still have the problem of not being able to change the private attributes to return the error when the function is called, and the idea of storing previously received errors is just terrible.

Do you guys have something in mind? One way around would be adding the decorator directly inside the library and have the access to the internals. Still, I believe the flexibility of using interfaces is far better.

**Comment by vmihailenco** [comment]
There is some kind of circuit breaker in master branch that is activated when Redis is down - https://github.com/go-redis/redis/blob/master/internal/pool/pool.go#L103-L137.

Probably you are looking for [Cmdable](http://godoc.org/github.com/go-redis/redis#Cmdable) interface.
